map_server:
  ros__parameters:
    image: mymap.pgm
    resolution: 0.020000
    origin: [-15.880000, -5.000000, 0.000000]
    negate: 0
    occupied_thresh: 0.65
    free_thresh: 0.196

costmap_filter_info_server:
  ros__parameters:
    type: 1
    filter_info_topic: "costmap_filter_info"
    mask_topic: "filter_mask"
    base: 0.0
    multiplier: 0.25